name: First Workflow

on: workflow_dispatch

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Paso que puede fallar
        continue-on-error: true
        id: step_1
        run: exit 0  # Simula un fallo

      - name: Paso en medio
        id: step_2
        run: echo hola

      - name: Ejecutar solo si `step_1` falló
        if: steps.step_1.outcome == 'failure'
        run: echo "El step_1 falló, así que estoy ejecutando este paso."

      - name: Paso normal
        run: 'echo "El resultado de step_2 fue: ${{ steps.step_2.outcome }}"'


      
