name: First Workflow

on: workflow_dispatch

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Step A
        id: step_a
        run: exit 1  # Simula un fallo

      - name: Step B
        id: step_b
        run: echo "Éxito en Step B"

      - name: Step C (evaluación en Bash)
        run: |
          if [ "${{ steps.step_b.outcome }}" == "failure" ]; then
            echo "entro al if"
          else
            echo "entro al else"
          fi




      
